
all:
	gcc -DVAR_PATH="\"prefix/var\"" -DTMP_PATH="\"/tmp/pako\"" package/install.c db/init.c db/read.c output/o.c package/parse.c package/arch.c package/specs_check.c package/unpack.c package/tar.c essentials/create.c -lsqlite3 -larchive
